DROP INDEX "articles_url_idx";--> statement-breakpoint
DROP INDEX "articles_title_idx";--> statement-breakpoint
DROP INDEX "articles_type_idx";--> statement-breakpoint
DROP INDEX "articles_fingerprint_idx";--> statement-breakpoint
DROP INDEX "articles_updated_at_idx";--> statement-breakpoint
DROP INDEX "feeds_duplicate_of_idx";--> statement-breakpoint
DROP INDEX "feeds_url_idx";--> statement-breakpoint
DROP INDEX "feeds_feed_type_idx";--> statement-breakpoint
DROP INDEX "feeds_valid_idx";--> statement-breakpoint
DROP INDEX "feeds_fingerprint_idx";--> statement-breakpoint
DROP INDEX "feeds_last_scraped_idx";--> statement-breakpoint
DROP INDEX "feeds_updated_at_idx";--> statement-breakpoint
DROP INDEX "folders_user_idx";--> statement-breakpoint
DROP INDEX "folders_created_at_idx";--> statement-breakpoint
DROP INDEX "folders_updated_at_idx";--> statement-breakpoint
DROP INDEX "follows_user_idx";--> statement-breakpoint
DROP INDEX "follows_alias_idx";--> statement-breakpoint
DROP INDEX "follows_created_at_idx";--> statement-breakpoint
DROP INDEX "follows_updated_at_idx";--> statement-breakpoint
DROP INDEX "likes_user_idx";--> statement-breakpoint
DROP INDEX "likes_created_at_idx";--> statement-breakpoint
DROP INDEX "listens_user_idx";--> statement-breakpoint
DROP INDEX "listens_created_at_idx";--> statement-breakpoint
DROP INDEX "listens_updated_at_idx";--> statement-breakpoint
DROP INDEX "reads_updated_at_idx";--> statement-breakpoint
DROP INDEX "stars_user_idx";--> statement-breakpoint
DROP INDEX "stars_updated_at_idx";--> statement-breakpoint
CREATE INDEX "listens_user_created_at_idx" ON "listens" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "stars_user_created_at_idx" ON "stars" USING btree ("user_id","created_at");